export const POST_MESSAGES = {
  POST_CREATED_SUCCESSFULLY: 'Post created successfully',
  SERVER_ERROR_DURING_POST_CREATION: 'Server error during post creation.',
  SERVER_ERROR_FETCHING_POSTS: 'Server error fetching posts',
  SERVER_ERROR_FETCHING_FEED: 'Server error fetching feed',
  SERVER_ERROR_FETCHING_USER_POSTS: 'Server error fetching user posts.',
  POST_UPDATED_SUCCESSFULLY: 'Post updated successfully',
  SERVER_ERROR_DURING_POST_UPDATE: 'Server error during post update.',
  POST_DELETED_SUCCESSFULLY: 'Post deleted successfully',
  SERVER_ERROR_DURING_POST_DELETION: 'Server error during post deletion.',
  POST_LIKED_SUCCESSFULLY: 'Post liked successfully',
  LIKE_REMOVED_SUCCESSFULLY: 'Like removed successfully',
  POST_DISLIKED_SUCCESSFULLY: 'Post disliked successfully',
  DISLIKE_REMOVED_SUCCESSFULLY: 'Dislike removed successfully',
  SERVER_ERROR_FETCHING_CATEGORIES: 'Server error fetching categories',
  SERVER_ERROR_FETCHING_POST_LIKES: 'Server error fetching post likes.',
  SERVER_ERROR_FETCHING_POST_DISLIKES: 'Server error fetching post dislikes.',
  CATEGORY_NOT_FOUND: 'Category not found',
};